CREATE TABLE IF NOT EXISTS reminder_dispatches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  local_date TEXT NOT NULL,
  sent_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, local_date),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
